### ISSUE TITLE
Bug in converting html attributes in batch mode

### ISSUE THREAD

**Issue by leakyMirror** [gruntjs/grunt-contrib-jade#130]
I am trying to convert ```jade``` files in ```src/jade``` to ```html``` and preserve folder structure. Here is my task:
```
  html:
    expand: true
    cwd: 'src/jade'
    ext: '.html'
    src: ['**/*.jade']
    dest: 'dev/'
``` 
Problem is in converting this kind of lines:

```jade
div(ui-view)
```

```html
<!--Actual: -->
<div ui-view="ui-view"></div>

<!--Expected:-->
<div ui-view></div>
````

The interesting part is that it works as expected with ```src/jade/index.jade```, but fails with ```src/jade/templates/home.jade```.
